# Generated by Django 6.0.5 on 2026-10-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_banner_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Enter one product feature per line.'),
        ),
    ]
